# Generated by Django 4.2.6 on 2024-02-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")], default="other", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(
                blank=True,
                choices=[
                    ("red", "Red"),
                    ("blue", "Blue"),
                    ("green", "Green"),
                    ("yellow", "Yellow"),
                    ("black", "Black"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.CharField(
                blank=True,
                choices=[("S", "S"), ("M", "M"), ("L", "L"), ("XL", "XL"), ("XXL", "XXL")],
                max_length=3,
                null=True,
            ),
        ),
    ]
