# Generated by Django 4.2.6 on 2024-02-06 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(blank=True, null=True, upload_to="event_images/")),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="SubEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("image", models.ImageField(blank=True, null=True, upload_to="subevent_images/")),
                ("subevent_date", models.DateTimeField()),
                ("description", models.TextField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="subevents", to="events.event"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendee",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                ("subevent", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="events.subevent")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "subevent")},
            },
        ),
    ]
