# Generated by Django 4.2.6 on 2024-02-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subevent",
            name="is_free",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subevent",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name="subevent",
            name="subevent_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
