# Generated by Django 4.2.6 on 2024-02-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_city_user_first_name_user_last_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="province_state",
            field=models.CharField(
                choices=[
                    ("", "Select Province/State"),
                    ("AB", "Alberta"),
                    ("BC", "British Columbia"),
                    ("MB", "Manitoba"),
                    ("NB", "New Brunswick"),
                    ("NL", "Newfoundland and Labrador"),
                    ("NS", "Nova Scotia"),
                    ("ON", "Ontario"),
                    ("PE", "Prince Edward Island"),
                    ("QC", "Quebec"),
                    ("SK", "Saskatchewan"),
                ],
                default="",
                max_length=2,
                verbose_name="Province/State",
            ),
        ),
    ]
