# Generated by Django 4.2.6 on 2024-02-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_province_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email_address", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=15)),
                ("street_address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("province_state", models.CharField(max_length=100)),
                ("postal_zip_code", models.CharField(max_length=10)),
                ("year", models.IntegerField()),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("show_n_shine", models.BooleanField(default=False)),
                ("poker_run", models.BooleanField(default=False)),
                ("cruise_night", models.BooleanField(default=False)),
                ("street_dance", models.BooleanField(default=False)),
                ("t_shirts_quantity", models.IntegerField(default=0)),
                ("toques_quantity", models.IntegerField(default=0)),
                ("baseball_caps_quantity", models.IntegerField(default=0)),
            ],
        ),
    ]
