# Generated by Django 4.2.6 on 2024-03-07 07:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_registration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="city",
        ),
        migrations.RemoveField(
            model_name="user",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="user",
            name="province_state",
        ),
        migrations.RemoveField(
            model_name="user",
            name="street_address",
        ),
    ]
