# Generated by Django 4.2.6 on 2024-03-08 05:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_user_city_remove_user_postal_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Merchandise",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("item_type", models.CharField(max_length=100)),
                ("size", models.CharField(blank=True, max_length=10, null=True)),
                ("color", models.CharField(max_length=50)),
                ("quantity", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("fname", models.CharField(max_length=100)),
                ("lname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("street", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("prov", models.CharField(max_length=100)),
                ("postal", models.CharField(max_length=10)),
                ("show_n_shine_participation", models.BooleanField(default=False)),
                ("poker_run_participation", models.BooleanField(default=False)),
                ("cruise_night_participation", models.BooleanField(default=False)),
                ("street_dance_participation", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.CharField(max_length=4)),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="vehicles", to="users.profile"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Registration",
        ),
        migrations.AddField(
            model_name="merchandise",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="merchandise", to="users.profile"
            ),
        ),
    ]
